export const YOUTUBE_API_KEY = import.meta.env.VITE_YOUTUBE_API_KEY;
export const YOUTUBE_API_BASE_URL = 'https://www.googleapis.com/youtube/v3';

export const NFL_TEAMS = [
  { name: 'Detroit Lions', searchQuery: 'Detroit Lions', color: 'hsl(210, 100%, 40%)' },
  { name: 'Green Bay Packers', searchQuery: 'Green Bay Packers', color: 'hsl(85, 60%, 35%)' },
  { name: 'Chicago Bears', searchQuery: 'Chicago Bears', color: 'hsl(20, 100%, 25%)' },
  { name: 'Minnesota Vikings', searchQuery: 'Minnesota Vikings', color: 'hsl(270, 60%, 40%)' },
  { name: 'Kansas City Chiefs', searchQuery: 'Kansas City Chiefs', color: 'hsl(0, 100%, 45%)' },
  { name: 'Las Vegas Raiders', searchQuery: 'Las Vegas Raiders', color: 'hsl(0, 0%, 20%)' },
  { name: 'Los Angeles Chargers', searchQuery: 'Los Angeles Chargers', color: 'hsl(195, 100%, 50%)' },
  { name: 'Denver Broncos', searchQuery: 'Denver Broncos', color: 'hsl(25, 100%, 45%)' },
  { name: 'Buffalo Bills', searchQuery: 'Buffalo Bills', color: 'hsl(215, 100%, 45%)' },
  { name: 'Miami Dolphins', searchQuery: 'Miami Dolphins', color: 'hsl(180, 100%, 40%)' },
  { name: 'New England Patriots', searchQuery: 'New England Patriots', color: 'hsl(220, 45%, 25%)' },
  { name: 'New York Jets', searchQuery: 'New York Jets', color: 'hsl(140, 60%, 30%)' },
  { name: 'Baltimore Ravens', searchQuery: 'Baltimore Ravens', color: 'hsl(270, 40%, 30%)' },
  { name: 'Cincinnati Bengals', searchQuery: 'Cincinnati Bengals', color: 'hsl(25, 100%, 45%)' },
  { name: 'Cleveland Browns', searchQuery: 'Cleveland Browns', color: 'hsl(25, 85%, 40%)' },
  { name: 'Pittsburgh Steelers', searchQuery: 'Pittsburgh Steelers', color: 'hsl(45, 100%, 50%)' },
  { name: 'Houston Texans', searchQuery: 'Houston Texans', color: 'hsl(215, 60%, 30%)' },
  { name: 'Indianapolis Colts', searchQuery: 'Indianapolis Colts', color: 'hsl(215, 100%, 45%)' },
  { name: 'Jacksonville Jaguars', searchQuery: 'Jacksonville Jaguars', color: 'hsl(180, 100%, 35%)' },
  { name: 'Tennessee Titans', searchQuery: 'Tennessee Titans', color: 'hsl(210, 100%, 40%)' },
  { name: 'Dallas Cowboys', searchQuery: 'Dallas Cowboys', color: 'hsl(210, 100%, 40%)' },
  { name: 'New York Giants', searchQuery: 'New York Giants', color: 'hsl(215, 100%, 45%)' },
  { name: 'Philadelphia Eagles', searchQuery: 'Philadelphia Eagles', color: 'hsl(170, 60%, 30%)' },
  { name: 'Washington Commanders', searchQuery: 'Washington Commanders', color: 'hsl(355, 85%, 40%)' },
  { name: 'Atlanta Falcons', searchQuery: 'Atlanta Falcons', color: 'hsl(0, 100%, 35%)' },
  { name: 'Carolina Panthers', searchQuery: 'Carolina Panthers', color: 'hsl(195, 100%, 40%)' },
  { name: 'New Orleans Saints', searchQuery: 'New Orleans Saints', color: 'hsl(45, 100%, 50%)' },
  { name: 'Tampa Bay Buccaneers', searchQuery: 'Tampa Bay Buccaneers', color: 'hsl(0, 100%, 40%)' },
  { name: 'Arizona Cardinals', searchQuery: 'Arizona Cardinals', color: 'hsl(355, 85%, 45%)' },
  { name: 'Los Angeles Rams', searchQuery: 'Los Angeles Rams', color: 'hsl(210, 100%, 45%)' },
  { name: 'San Francisco 49ers', searchQuery: 'San Francisco 49ers', color: 'hsl(0, 100%, 45%)' },
  { name: 'Seattle Seahawks', searchQuery: 'Seattle Seahawks', color: 'hsl(210, 100%, 35%)' },
];
