export const YOUTUBE_API_KEY = import.meta.env.VITE_YOUTUBE_API_KEY;
export const YOUTUBE_API_BASE_URL = 'https://www.googleapis.com/youtube/v3';

export const NFL_TEAMS = [
  { name: 'Detroit Lions', searchQuery: 'Detroit Lions NFL official', color: 'hsl(210, 100%, 40%)' },
  { name: 'Green Bay Packers', searchQuery: 'Green Bay Packers NFL official', color: 'hsl(85, 60%, 35%)' },
  { name: 'Chicago Bears', searchQuery: 'Chicago Bears NFL official', color: 'hsl(20, 100%, 25%)' },
  { name: 'Minnesota Vikings', searchQuery: 'Minnesota Vikings NFL official', color: 'hsl(270, 60%, 40%)' },
  { name: 'Kansas City Chiefs', searchQuery: 'Kansas City Chiefs NFL official', color: 'hsl(0, 100%, 45%)' },
  { name: 'Las Vegas Raiders', searchQuery: 'Las Vegas Raiders NFL official', color: 'hsl(0, 0%, 20%)' },
  { name: 'Los Angeles Chargers', searchQuery: 'Los Angeles Chargers NFL official', color: 'hsl(195, 100%, 50%)' },
  { name: 'Denver Broncos', searchQuery: 'Denver Broncos NFL official', color: 'hsl(25, 100%, 45%)' },
  { name: 'Buffalo Bills', searchQuery: 'Buffalo Bills NFL official', color: 'hsl(215, 100%, 45%)' },
  { name: 'Miami Dolphins', searchQuery: 'Miami Dolphins NFL official', color: 'hsl(180, 100%, 40%)' },
  { name: 'New England Patriots', searchQuery: 'New England Patriots NFL official', color: 'hsl(220, 45%, 25%)' },
  { name: 'New York Jets', searchQuery: 'New York Jets NFL official', color: 'hsl(140, 60%, 30%)' },
  { name: 'Baltimore Ravens', searchQuery: 'Baltimore Ravens NFL official', color: 'hsl(270, 40%, 30%)' },
  { name: 'Cincinnati Bengals', searchQuery: 'Cincinnati Bengals NFL official', color: 'hsl(25, 100%, 45%)' },
  { name: 'Cleveland Browns', searchQuery: 'Cleveland Browns NFL official', color: 'hsl(25, 85%, 40%)' },
  { name: 'Pittsburgh Steelers', searchQuery: 'Pittsburgh Steelers NFL official', color: 'hsl(45, 100%, 50%)' },
  { name: 'Houston Texans', searchQuery: 'Houston Texans NFL official', color: 'hsl(215, 60%, 30%)' },
  { name: 'Indianapolis Colts', searchQuery: 'Indianapolis Colts NFL official', color: 'hsl(215, 100%, 45%)' },
  { name: 'Jacksonville Jaguars', searchQuery: 'Jacksonville Jaguars NFL official', color: 'hsl(180, 100%, 35%)' },
  { name: 'Tennessee Titans', searchQuery: 'Tennessee Titans NFL official', color: 'hsl(210, 100%, 40%)' },
  { name: 'Dallas Cowboys', searchQuery: 'Dallas Cowboys NFL official', color: 'hsl(210, 100%, 40%)' },
  { name: 'New York Giants', searchQuery: 'New York Giants NFL official', color: 'hsl(215, 100%, 45%)' },
  { name: 'Philadelphia Eagles', searchQuery: 'Philadelphia Eagles NFL official', color: 'hsl(170, 60%, 30%)' },
  { name: 'Washington Commanders', searchQuery: 'Washington Commanders NFL official', color: 'hsl(355, 85%, 40%)' },
  { name: 'Atlanta Falcons', searchQuery: 'Atlanta Falcons NFL official', color: 'hsl(0, 100%, 35%)' },
  { name: 'Carolina Panthers', searchQuery: 'Carolina Panthers NFL official', color: 'hsl(195, 100%, 40%)' },
  { name: 'New Orleans Saints', searchQuery: 'New Orleans Saints NFL official', color: 'hsl(45, 100%, 50%)' },
  { name: 'Tampa Bay Buccaneers', searchQuery: 'Tampa Bay Buccaneers NFL official', color: 'hsl(0, 100%, 40%)' },
  { name: 'Arizona Cardinals', searchQuery: 'Arizona Cardinals NFL official', color: 'hsl(355, 85%, 45%)' },
  { name: 'Los Angeles Rams', searchQuery: 'Los Angeles Rams NFL official', color: 'hsl(210, 100%, 45%)' },
  { name: 'San Francisco 49ers', searchQuery: 'San Francisco 49ers NFL official', color: 'hsl(0, 100%, 45%)' },
  { name: 'Seattle Seahawks', searchQuery: 'Seattle Seahawks NFL official', color: 'hsl(210, 100%, 35%)' },
];
